# Generated by Django 6.0.7 on 2026-09-25 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0018_rename_name_productvariant_title'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordergroup',
            old_name='customer',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='catalogs.productvariant'),
        ),
    ]
