# Generated by Django 6.0.7 on 2026-08-01 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='title')),
            ],
            options={
                'verbose_name': 'option group',
                'verbose_name_plural': 'option groups',
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='slug'),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='title')),
                ('type', models.CharField(choices=[('text', 'Text'), ('boolean', 'Boolean'), ('integer', 'Integer'), ('float', 'Float'), ('date', 'Date'), ('datetime', 'DateTime'), ('option_group', 'Option Group'), ('option', 'Option'), ('multi_option', 'Multi Option')], default='text', max_length=20, verbose_name='type')),
                ('required', models.BooleanField(default=False, verbose_name='required')),
                ('option_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='option_attributes', to='catalogs.optiongroup', verbose_name='option group')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
            },
        ),
        migrations.CreateModel(
            name='OptionGroupValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='title')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='catalogs.optiongroup', verbose_name='group')),
            ],
            options={
                'verbose_name': 'option group value',
                'verbose_name_plural': 'option group values',
            },
        ),
        migrations.CreateModel(
            name='ProductClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='title')),
                ('description', models.CharField(blank=True, max_length=2048, null=True, verbose_name='description')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='slug')),
                ('track_stock', models.BooleanField(default=True, verbose_name='track stock')),
                ('require_shipping', models.BooleanField(default=True, verbose_name='require shipping')),
                ('options', models.ManyToManyField(blank=True, related_name='product_classes', to='catalogs.option', verbose_name='options')),
            ],
            options={
                'verbose_name': 'product class',
                'verbose_name_plural': 'product classes',
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='title')),
                ('type', models.CharField(choices=[('text', 'Text'), ('boolean', 'Boolean'), ('integer', 'Integer'), ('float', 'Float'), ('date', 'Date'), ('datetime', 'DateTime'), ('option_group', 'Option Group'), ('option', 'Option'), ('multi_option', 'Multi Option')], default='text', max_length=20, verbose_name='type')),
                ('required', models.BooleanField(default=False, verbose_name='required')),
                ('option_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attributes', to='catalogs.optiongroup', verbose_name='option group')),
                ('product_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_attributes', to='catalogs.productclass', verbose_name='product class')),
            ],
            options={
                'verbose_name': 'product attribute',
                'verbose_name_plural': 'product attributes',
            },
        ),
    ]
