# Generated by Django 6.0.7 on 2026-08-06 12:36

import django.db.models.deletion
import libs.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_optiongroup_alter_category_slug_option_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure', models.CharField(choices=[('standalone', 'Standalone'), ('parent', 'Parent'), ('child', 'Child')], default='standalone', max_length=20, verbose_name='structure')),
                ('is_public', models.BooleanField(default=True, verbose_name='is public')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='title')),
                ('upc', libs.db.fields.UpperCaseCharField(blank=True, max_length=12, null=True, unique=True, verbose_name='upc')),
                ('description', models.CharField(blank=True, max_length=2048, null=True, verbose_name='description')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='slug')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='meta title')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='meta description')),
                ('meta_keywords', models.CharField(blank=True, max_length=1024, null=True, verbose_name='meta keywords')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalogs.category', verbose_name='category')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalogs.product', verbose_name='parent')),
                ('product_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalogs.productclass', verbose_name='product class')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, null=True, verbose_name='value text')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_value', to='catalogs.productattribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_value', to='catalogs.product')),
            ],
            options={
                'verbose_name': 'attribute value',
                'verbose_name_plural': 'attribute values',
                'unique_together': {('product', 'attribute')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='products', through='catalogs.ProductAttributeValue', to='catalogs.productattribute', verbose_name='attributes'),
        ),
    ]
