# Generated by Django 6.0.7 on 2026-08-08 18:25

import django.db.models.deletion
import libs.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_product_productattributevalue_product_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributevalue',
            name='value_boolean',
            field=models.BooleanField(blank=True, null=True, verbose_name='value boolean'),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='value_float',
            field=models.FloatField(blank=True, null=True, verbose_name='value float'),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='value_integer',
            field=models.IntegerField(blank=True, null=True, verbose_name='value integer'),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='value_multi_option',
            field=models.ManyToManyField(blank=True, related_name='attribute_value_multi', to='catalogs.optiongroupvalue'),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='value_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attribute_value', to='catalogs.optiongroupvalue'),
        ),
        migrations.AlterField(
            model_name='product',
            name='upc',
            field=libs.db.fields.UpperCaseCharField(blank=True, help_text='uniq company num', max_length=12, null=True, unique=True, verbose_name='upc'),
        ),
        migrations.CreateModel(
            name='ProductRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(default=0, verbose_name='rank')),
                ('primary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_recommendations', to='catalogs.product')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='catalogs.product')),
            ],
            options={
                'verbose_name': 'product recommendation',
                'verbose_name_plural': 'product recommendations',
                'ordering': ['primary', '-rank'],
                'unique_together': {('primary', 'recommendation')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='recommended_products',
            field=models.ManyToManyField(blank=True, related_name='recommended_by', through='catalogs.ProductRecommendation', to='catalogs.product', verbose_name='recommended products'),
        ),
    ]
