# Generated by Django 6.0.7 on 2026-08-08 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0005_product_created_at_product_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products_categories', to='catalogs.category', verbose_name='categories'),
        ),
    ]
