# Generated by Django 6.0.7 on 2026-08-13 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0006_product_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='تصویر')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalogs.category', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر دسته بندی',
                'verbose_name_plural': 'تصاویر دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='LastOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_price', models.PositiveIntegerField(verbose_name='قیمت با تخفیف')),
                ('offer_time', models.DateTimeField(verbose_name='زمان باقیمانده')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_offer', to='catalogs.product', verbose_name='آخرین پیشنهاد')),
            ],
            options={
                'verbose_name': 'آخرین پیشنهاد',
                'verbose_name_plural': 'آخرین پیشنهاد ها',
            },
        ),
    ]
