# Generated by Django 6.0.7 on 2026-08-14 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0007_categoryimages_lastoffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='title')),
                ('description', models.CharField(blank=True, max_length=2048, null=True, verbose_name='description')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'product brand',
                'verbose_name_plural': 'product brands',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalogs.productbrand', verbose_name='brand'),
        ),
    ]
