# Generated by Django 6.0.7 on 2026-08-14 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0008_productbrand_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='title'),
        ),
    ]
