# Generated by Django 6.0.7 on 2026-08-14 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0009_remove_product_brand_alter_productbrand_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalogs.productbrand', verbose_name='brand'),
        ),
    ]
