# Generated by Django 6.0.7 on 2026-09-21 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0016_remove_product_category_productvariant'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='title')),
            ],
            options={
                'verbose_name': 'Variant Option',
                'verbose_name_plural': 'Variant Options',
            },
        ),
        migrations.CreateModel(
            name='VariantOptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='title')),
            ],
            options={
                'verbose_name': 'variant option group',
                'verbose_name_plural': 'variant option groups',
            },
        ),
        migrations.CreateModel(
            name='VariantOptionGroupValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='title')),
            ],
            options={
                'verbose_name': 'option group value',
                'verbose_name_plural': 'option group values',
            },
        ),
        migrations.CreateModel(
            name='ProductAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about', to='catalogs.product')),
            ],
            options={
                'verbose_name': 'product about',
                'verbose_name_plural': 'product abouts',
            },
        ),
    ]
