# Generated by Django 6.0.7 on 2026-09-21 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0017_variantoption_variantoptiongroup_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='name',
            new_name='title',
        ),
    ]
