# Generated by Django 6.0.7 on 2026-09-29 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0018_rename_name_productvariant_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='productabout',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProductVariantAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about', to='catalogs.productvariant')),
            ],
            options={
                'verbose_name': 'product variant about',
                'verbose_name_plural': 'product variant abouts',
            },
        ),
    ]
