# Generated by Django 6.0.7 on 2026-08-12 02:28

import apps.home.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0006_product_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopSliderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='تایتل')),
                ('image', models.ImageField(upload_to=apps.home.models.slider_directory_path, verbose_name='اسلایدر بالا')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_sliders', to='catalogs.product')),
            ],
            options={
                'verbose_name': 'اسلایدر بالا',
                'verbose_name_plural': 'اسلایدرهای بالا',
            },
        ),
    ]
