# Generated by Django 6.0.7 on 2026-08-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topslidermodel',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس'),
        ),
    ]
