# Generated by Django 6.0.7 on 2026-09-25 15:27

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0018_rename_name_productvariant_title'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='مشتری'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ ثبت سفارش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date_done',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تکمیل سفارش'),
        ),
        migrations.CreateModel(
            name='OrderedVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='تعداد')),
                ('product_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت محصول')),
                ('product_off_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت با تخفیف')),
                ('description', models.CharField(max_length=256, verbose_name='توضیحات')),
                ('status', models.BooleanField(default=False, verbose_name='گزارش')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_variants', to='payments.order')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_variants', to='catalogs.productvariant')),
            ],
        ),
        migrations.DeleteModel(
            name='OrderedProduct',
        ),
    ]
