# Generated by Django 6.0.7 on 2026-09-25 15:32

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_order_customer_order_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=django_jalali.db.models.jDateField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت سفارش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date_done',
            field=django_jalali.db.models.jDateField(blank=True, default=None, null=True, verbose_name='تاریخ تکمیل سفارش'),
        ),
    ]
