# Generated by Django 6.0.7 on 2026-08-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrecord',
            name='in_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='offer_price',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
