# Generated by Django 6.0.7 on 2026-09-19 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0016_remove_product_category_productvariant'),
        ('inventory', '0002_stockrecord_in_offer_stockrecord_offer_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockrecord',
            old_name='num_stock',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='stockrecord',
            old_name='threshold_low_stack',
            new_name='threshold_low_stock',
        ),
        migrations.RemoveField(
            model_name='stockrecord',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stockrecord',
            name='sku',
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='reserved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='variant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stockrecord', to='catalogs.productvariant'),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('return', 'Return'), ('damage', 'Damage'), ('adjustment', 'Adjustment'), ('initial', 'Initial Stock')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('quantity_before', models.PositiveIntegerField()),
                ('quantity_after', models.PositiveIntegerField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stockrecord')),
            ],
        ),
    ]
