# Generated by Django 6.0.7 on 2026-08-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, height_field='height', null=True, upload_to='images/', width_field='width')),
                ('width', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('height', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('file_hash', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('focal_point_x', models.FloatField(blank=True, null=True)),
                ('focal_point_y', models.FloatField(blank=True, null=True)),
                ('focal_point_width', models.FloatField(blank=True, null=True)),
                ('focal_point_height', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'media_images',
            },
        ),
    ]
